<?php

/**
 * Implementation of hook_permission().
 */
function mysearch_permission() {
  return array(
    'access mysearch' => array(
        'title' => 'Access My Search',
        'description' => 'Allows a user to access search results',
      )
    );
}


/**
 * Implementation of hook_menu().
 */
function mysearch_menu() {
  $items['mysearch/%'] = array(
    'title' => t('Search'),
    'page callback' => 'mysearch_searchpage',
    'access arguments' => array('access mysearch'),
    'type' => MENU_SUGGESTED_ITEM,
  );
  return $items;
}


/**
 * Menu callback provides a simple list of nodes matching the
 * search term Example: hitting the URL:
 *   http://domain.com/mysearch/example
 * will return a list of links to nodes which have the word
 * example in them.
 */
function mysearch_searchpage() {
  $searchterm = arg(1);
  $search_results = db_select('field_data_body', 'db')
    ->fields('db', array('entity_id'))
    ->condition('db.body_value', '%' . db_like($searchterm) . '%', 'LIKE')
    ->execute();
  if ($search_results->rowCount() != 0) {
    foreach($search_results as $record) {
      $node = node_load($record->entity_id);
      $output[] = l($node->title, 'node/' . $node->nid, array('attributes' => array('title' => $node->title)));
    }
    $output = theme('item_list', array('items' => $output));
  } else {
    $output = t('No data');
  }
  return $output;
}